#!/usr/bin/env python3
"""Generate web/mobile.css: a phone-only 12px floor for text the desktop CSS sets at 9-11.5px.

The app is intentionally dense on desktop (11px labels, 10px badges), which is unreadable on a
phone. Rather than change desktop, this scans styles.css and theme.css for top-level rules
that declare a small font-size and emits `@media (max-width: 640px)` overrides raising them to
12px. Re-run after adding new small-text rules:

    python scripts/gen_mobile_type_floor.py
"""
from __future__ import annotations

import re
from pathlib import Path

WEB = Path(__file__).resolve().parent.parent / "web"
SOURCES = ("styles.css", "theme.css")
FLOOR_PX = 12
SMALL_RE = re.compile(r"font-size\s*:\s*(\d+(?:\.\d+)?)px(\s*!important)?", re.IGNORECASE)
INLINE_SIZES = ("9", "10", "10.5", "11", "11.5")


def top_level_rules(css: str):
    """Yield (selector, body) for style rules that are not inside any at-rule."""
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)
    stack: list[bool] = []  # one entry per open block; True when that block is an at-rule
    sel_start = 0
    sel = ""
    body_start = 0
    for i, ch in enumerate(css):
        if ch == "{":
            head = css[sel_start:i].strip()
            is_at = head.startswith("@")
            if not any(stack) and not is_at:
                sel, body_start = head, i + 1
            stack.append(is_at)
            sel_start = i + 1
        elif ch == "}":
            if stack:
                was_at = stack.pop()
                if not was_at and not any(stack) and sel:
                    yield sel, css[body_start:i]
                    sel = ""
            sel_start = i + 1
        elif ch == ";" and not stack:
            sel_start = i + 1


def main() -> None:
    normal: dict[str, None] = {}
    important: dict[str, None] = {}
    for name in SOURCES:
        for sel, body in top_level_rules((WEB / name).read_text(encoding="utf-8")):
            if "@" in sel or "%" in sel:  # keyframe steps etc.
                continue
            small = [(float(size), bool(imp)) for size, imp in SMALL_RE.findall(body) if 0 < float(size) < FLOOR_PX]
            if not small:
                continue
            bucket = important if any(imp for _, imp in small) else normal
            for one in (part.strip() for part in sel.split(",")):
                if one and not one.startswith(":root"):
                    bucket[one] = None
    # A selector that is !important anywhere must be !important here too, or the source wins.
    normal = {k: None for k in normal if k not in important}

    inline = [f'[style*="font-size:{v}px"]' for v in INLINE_SIZES] + [f'[style*="font-size: {v}px"]' for v in INLINE_SIZES]
    # One rule per selector: a single selector the browser can't parse would otherwise
    # invalidate its whole comma-separated group.
    lines = [
        "/* GENERATED by scripts/gen_mobile_type_floor.py - do not edit by hand.",
        f"   Phone-only {FLOOR_PX}px floor for text the desktop CSS sets at 9-11.5px. */",
        "@media (max-width: 640px) {",
        *[f"  {sel} {{ font-size: {FLOOR_PX}px; }}" for sel in sorted(normal)],
        # Inline style="font-size: 11px" in JS-built markup, and source rules that use
        # !important, can only be beaten with !important.
        *[f"  {sel} {{ font-size: {FLOOR_PX}px !important; }}" for sel in sorted(important) + inline],
        "}",
        "",
    ]
    (WEB / "mobile.css").write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(normal)} normal + {len(important)} !important selectors -> web/mobile.css")


if __name__ == "__main__":
    main()
